# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAplication', '0002_hospital_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='hospital',
        ),
    ]
